parameters:
#    range_find_one_click.example.class: Range\FindOneClickBundle\Example

services:
#    range_find_one_click.example:
#        class: %range_find_one_click.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
